steps:
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: sh
  args: ["-c","terraform init"]
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: sh
  args: ["-c","terraform plan"]
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: sh
  args: ["-c","terraform refresh"]
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: sh
  args: ["-c","terraform apply -replace="google_compute_network.main""]
